In [1]:
#IMPORT LIBRARIES
import numpy as np # our numerical workhorse
import matplotlib.pyplot as plt # plotting library
import seaborn as sns # extra plotting features
import skimage.io 

In [2]:
#READ THE IMAGE 
im = skimage.io.imread('HandImages/1.jpeg')

In [3]:
#RUNNING MATPLOTLIB IN BACKEND
%matplotlib

Using matplotlib backend: Qt5Agg


In [4]:
# CHOOSE THE HAND REGIONS AND GET THE COORDINATE VALUES OF THE LOADED IMAGE
with sns.axes_style("white"):
    plt.imshow(im)
clicks_Hand = plt.ginput(60)
clicks_Hand

[(365.4954163483575, 982.9054349012331),
 (324.6354359925788, 957.7608316053693),
 (362.3523409363745, 879.1839463057948),
 (415.7846229400851, 857.182418421914),
 (444.0723016479318, 800.6070610062205),
 (554.0799410673361, 696.8855724107823),
 (554.0799410673361, 696.8855724107823),
 (450.35845247189775, 649.7394412310376),
 (525.7922623594892, 640.3102149950887),
 (513.2199607115573, 520.8733493397357),
 (538.3645640074211, 395.1503328604167),
 (535.2214885954382, 310.2872967368763),
 (525.7922623594892, 178.2781294335914),
 (349.7800392884426, 215.99503437738713),
 (340.35081305249366, 294.57191967696144),
 (356.06619011240855, 370.0057295645529),
 (371.78156717232343, 442.29646404016125),
 (371.78156717232343, 514.5871985157697)]

In [6]:
#STORE THE VALUES OF THE COORDINATES IN THE FORM OF RGB VALUES INTO AN ARRAY CALLED HAND_ARR FOR HAND REGIONS OF 1 IMAGE
from PIL import Image
Hand_final = []
img = Image.open('HandImages/1.jpeg')
img.show()
for index, tuple in enumerate(clicks_Hand):
    x = tuple[0]
    y = tuple[1]
    pvVal = img.getpixel((x,y))
    Hand_final.append(pvVal)
Hand_arr = np.asarray(Hand_final)
leng1 = len(Hand_arr)
base1_array_1d = np.ones(leng1)
Hand_arr = np.column_stack((Hand_arr, base1_array_1d))
Hand_arr

array([[212., 165., 119.,   1.],
       [226., 182., 135.,   1.],
       [183., 132.,  87.,   1.],
       [165., 113.,  74.,   1.],
       [146., 104.,  62.,   1.],
       [225., 171., 127.,   1.],
       [225., 171., 127.,   1.],
       [149.,  93.,  58.,   1.],
       [224., 166., 118.,   1.],
       [188., 127.,  83.,   1.],
       [156.,  96.,  59.,   1.],
       [192., 131.,  87.,   1.],
       [209., 130.,  87.,   1.],
       [194., 116.,  70.,   1.],
       [225., 144., 101.,   1.],
       [217., 150., 105.,   1.],
       [178., 114.,  76.,   1.],
       [214., 147., 105.,   1.]])

In [7]:
#STORE THE VALUES OF THE COORDINATES IN THE FORM OF RGB VALUES INTO AN ARRAY CALLED HAND_ARR FOR HAND REGIONS OF 1 IMAGE
with sns.axes_style("white"):
    plt.imshow(im)
clicks_nonHand = plt.ginput(60)

In [8]:
from PIL import Image
nonHand_final = []
img = Image.open('HandImages/1.jpeg')
img.show()
for index, tuple in enumerate(clicks_nonHand):
    x = tuple[0]
    y = tuple[1]
    pvVal = img.getpixel((x,y))
    nonHand_final.append(pvVal)
nonHand_arr = np.asarray(nonHand_final)
leng = len(nonHand_arr)
base_array_1d = np.zeros(leng)
nonHand_arr = np.column_stack((nonHand_arr, base_array_1d)) 
print(nonHand_arr)
#REPEATED THE PROCESS FOR OTHER IMAGES AND STORED THEM IN A CSV TO TRAIN THE SVM CLASSIFIER

[[25. 26. 21.  0.]
 [26. 27. 21.  0.]
 [33. 34. 29.  0.]
 [30. 31. 26.  0.]
 [30. 31. 26.  0.]
 [22. 22. 20.  0.]
 [25. 26. 20.  0.]
 [26. 27. 22.  0.]
 [25. 26. 21.  0.]
 [22. 23. 18.  0.]
 [13. 13. 11.  0.]
 [ 4.  4.  4.  0.]
 [10.  6.  7.  0.]
 [14. 13. 11.  0.]
 [21. 21. 19.  0.]
 [13. 14. 16.  0.]
 [14. 12. 17.  0.]
 [14. 14. 22.  0.]
 [13. 12. 18.  0.]
 [14. 14. 16.  0.]
 [12. 11. 17.  0.]
 [ 9.  8. 13.  0.]
 [ 9.  8. 13.  0.]
 [ 8.  8. 10.  0.]
 [ 9.  9.  9.  0.]
 [11. 11. 11.  0.]
 [29. 28. 23.  0.]
 [29. 28. 23.  0.]
 [30. 31. 25.  0.]]


In [9]:
# IMPORTING LIBRARIES
import pandas as pd
import numpy as np
my_sheet = 'Sheet1' 
file_name = 'Input.csv' 

# READ THE INPUT CSV AND STORE IN A DATAFRAME
cell_df = pd.read_csv(file_name)
print(cell_df)

       R   G   B  Class
0     34  38  39      0
1     34  38  39      0
2     34  38  39      0
3     34  38  39      0
4     34  38  39      0
...   ..  ..  ..    ...
9995  18  12  16      0
9996  16  12  13      0
9997  16  12  13      0
9998  16  12  13      0
9999  17  13  14      0

[10000 rows x 4 columns]


In [10]:
cell_df.columns
#STORING THE FEATURES AND CLASS IN SEPERATE DATAFRAMES
feature_df = cell_df[['R','G','B']]
X = np.asarray(feature_df)
Y = np.asarray(cell_df['Class'])

In [11]:
#USING THE SCIKIT LEARN MODEL - TRAIN TEST SPLIT FUNCTION 

#Set the value of size to 0.2 to take 20% of data for testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [12]:
#USING SVM FROM SKLEARN TO TRAIN THE CLASSIFIER AND PREDICTING THE VALUES
#Predicting the labels for the input pixel values
from sklearn import svm
classifier = svm.SVC(kernel='linear', gamma = 'auto', C=2)
classifier.fit(X_train,y_train)
y_predict=classifier.predict(X_test)
X_test

array([[178, 136, 111],
       [238, 180, 160],
       [ 26,  22,  19],
       ...,
       [197, 162, 134],
       [ 39,  43,  44],
       [242, 201, 181]], dtype=int64)

In [13]:
#Confusion matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1119
           1       1.00      1.00      1.00       881

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000



In [14]:
y_predict

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [15]:
#PREDICTION RESULT - ARRAY OF PIXELS AND LABELS
prediction_result = np.column_stack((X_test, y_predict)) 
prediction_result

array([[178, 136, 111,   1],
       [238, 180, 160,   1],
       [ 26,  22,  19,   0],
       ...,
       [197, 162, 134,   1],
       [ 39,  43,  44,   0],
       [242, 201, 181,   1]], dtype=int64)

In [16]:
#TRYING TO PREDICT THE LABELS BY READING A NEW SHEET WITH PIXELS FOR NEW IMAGE
from pandas import read_excel
my_sheet = 'Sheet1' 
file_name = 'Test.xlsx' 
X_Test_df = read_excel(file_name, sheet_name = my_sheet)


In [17]:
#STORING THE FEATURES IN THE SEPERATE ARRAY
Testfeature_df = X_Test_df[['R','G','B']]
X_Test_arr = np.asarray(Testfeature_df)
y_predict_new=classifier.predict(X_Test_arr)

In [18]:

import cv2
from PIL import Image
#img = Image.open("HandImages/8.jpeg")
#new_size = img.resize((1000, 1000))
new_size = cv2.imread('Input_Hand_Images/6.jpg')
new_size = cv2.cvtColor(new_size, cv2.COLOR_BGR2RGB)
new_size.shape

(1000, 1000, 3)

In [19]:
# PRINTING THE SEGMENTED IMAGE
X_test_fin = np.uint8(X_Test_arr)
Result = X_test_fin[y_predict_new.flatten()]
res2 = Result.reshape(new_size.shape)
res2 = cv2.cvtColor(res2, cv2.COLOR_BGR2RGB)
cv2.imwrite('SVM_segmentedImage.jpg', res2)

True

In [20]:
import matplotlib.pyplot as plt
plt.imshow(res2)
plt.show()